# Generated by Django 2.1 on 2019-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wx_wxb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_name', models.CharField(max_length=20, verbose_name='公众号名称')),
                ('read', models.CharField(max_length=20, verbose_name='阅读数')),
                ('wx_url', models.URLField(max_length=1000, verbose_name='原文链接')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=100000, verbose_name='内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公众号文章',
            },
        ),
    ]
