# Generated by Django 2.1 on 2019-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='bedroom',
            field=models.CharField(max_length=20, verbose_name='房型'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='floor',
            field=models.CharField(max_length=60, verbose_name='楼层'),
        ),
    ]
